version: 2.1
executors:
  normal:
    docker:
      - image: "circleci/node:14-browsers"
orbs:
  node: circleci/node@4.1.0
jobs:
  checkout-code:
    executor: "normal"
    steps:
      - checkout
      - restore_cache:
          key: v1-yarn-cache-{{ .Branch }}-{{checksum "yarn.lock"}}

      - run: yarn

      - save_cache:
          key: v1-yarn-cache-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - node_modules/

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project/

  test:
    executor: "normal"
    steps:
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run YARN tests
          command: yarn run test
      - store_test_results:
          path: "coverage/clover.xml"
      - store_artifacts:
          path: "coverage/"

workflows:
  branch-build:
    jobs:
      - checkout-code
      - test:
          requires:
            - checkout-code
