version: 2.1
executors:
  normal:
    docker:
      - image: "circleci/node:14-browsers"
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    executor: "normal"
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run YARN tests
          command: yarn run test

workflows:
  test_my_app:
    jobs:
      - test
